"""Tests for the snapshot generator (engine/snapshot.py).

Covers:
- Snapshot from mock Group list with instances
- Empty group list
- Groups with no instances
- Correct field mapping (simplified names)
- YAML header comments present
- Groups organized by ad_format
- Instance rate omission when None
- Platform inclusion when provided
"""

from __future__ import annotations

from io import StringIO

from ruamel.yaml import YAML

from admedi.engine.snapshot import generate_snapshot
from admedi.models.enums import AdFormat, Platform
from admedi.models.group import Group
from admedi.models.instance import Instance


def _make_instance(
    instance_id: int = 1,
    name: str = "ironSource Default",
    network: str = "ironSource",
    is_bidder: bool = True,
    group_rate: float | None = 0.5,
) -> Instance:
    """Helper to create an Instance for testing."""
    return Instance.model_validate({
        "id": instance_id,
        "name": name,
        "networkName": network,
        "isBidder": is_bidder,
        "groupRate": group_rate,
    })


def _make_group(
    group_name: str = "US Tier 1",
    ad_format: str = "interstitial",
    countries: list[str] | None = None,
    position: int = 1,
    group_id: int | None = 100,
    floor_price: float | None = None,
    ab_test: str | None = None,
    instances: list[Instance] | None = None,
) -> Group:
    """Helper to create a Group for testing."""
    data: dict = {
        "groupName": group_name,
        "adFormat": ad_format,
        "countries": countries or ["US"],
        "position": position,
    }
    if group_id is not None:
        data["groupId"] = group_id
    if floor_price is not None:
        data["floorPrice"] = floor_price
    if ab_test is not None:
        data["abTest"] = ab_test
    if instances is not None:
        data["instances"] = [
            inst.model_dump(by_alias=True) for inst in instances
        ]
    return Group.model_validate(data)


def _parse_yaml(yaml_str: str) -> dict:
    """Parse a YAML string, stripping header comments."""
    yaml = YAML(typ="safe")
    return yaml.load(StringIO(yaml_str))


class TestSnapshotHeader:
    """Tests for YAML header comments."""

    def test_header_contains_generated_by(self) -> None:
        """Header includes the 'Generated by admedi snapshot' line."""
        result = generate_snapshot([], "key1", "Test App")
        assert "# Generated by admedi snapshot" in result

    def test_header_contains_app_info(self) -> None:
        """Header includes app name and key."""
        result = generate_snapshot([], "abc123", "My Game")
        assert "# App: My Game (abc123)" in result

    def test_header_contains_captured_timestamp(self) -> None:
        """Header includes a Captured timestamp line."""
        result = generate_snapshot([], "key1", "Test App")
        lines = result.split("\n")
        captured_lines = [l for l in lines if l.startswith("# Captured:")]
        assert len(captured_lines) == 1
        # Timestamp should have ISO-like format with 'T' separator
        timestamp_part = captured_lines[0].replace("# Captured: ", "")
        assert "T" in timestamp_part
        assert timestamp_part.endswith("Z")

    def test_header_order(self) -> None:
        """Header comments appear in the correct order."""
        result = generate_snapshot([], "key1", "Test App")
        lines = result.split("\n")
        comment_lines = [l for l in lines if l.startswith("#")]
        assert len(comment_lines) == 3
        assert comment_lines[0] == "# Generated by admedi snapshot"
        assert comment_lines[1].startswith("# App:")
        assert comment_lines[2].startswith("# Captured:")


class TestSnapshotTopLevel:
    """Tests for top-level YAML data fields."""

    def test_app_key_in_data(self) -> None:
        """app_key appears as a data field."""
        result = generate_snapshot([], "key1", "Test App")
        data = _parse_yaml(result)
        assert data["app_key"] == "key1"

    def test_app_name_in_data(self) -> None:
        """app_name appears as a data field."""
        result = generate_snapshot([], "key1", "Test App")
        data = _parse_yaml(result)
        assert data["app_name"] == "Test App"

    def test_platform_included_when_provided(self) -> None:
        """platform field is included when a Platform is passed."""
        result = generate_snapshot([], "key1", "Test App", platform=Platform.IOS)
        data = _parse_yaml(result)
        assert data["platform"] == "iOS"

    def test_platform_omitted_when_none(self) -> None:
        """platform field is not present when no platform is provided."""
        result = generate_snapshot([], "key1", "Test App")
        data = _parse_yaml(result)
        assert "platform" not in data

    def test_platform_android(self) -> None:
        """Platform.ANDROID serializes correctly."""
        result = generate_snapshot([], "key1", "Test App", platform=Platform.ANDROID)
        data = _parse_yaml(result)
        assert data["platform"] == "Android"


class TestSnapshotEmptyGroups:
    """Tests for empty group list behavior."""

    def test_empty_groups_produces_valid_yaml(self) -> None:
        """Empty group list produces valid YAML."""
        result = generate_snapshot([], "key1", "Test App")
        data = _parse_yaml(result)
        assert data is not None

    def test_empty_groups_has_groups_key(self) -> None:
        """Empty group list includes 'groups' key in output."""
        result = generate_snapshot([], "key1", "Test App")
        data = _parse_yaml(result)
        assert "groups" in data

    def test_empty_groups_section_is_empty_dict(self) -> None:
        """Empty group list produces empty groups dict."""
        result = generate_snapshot([], "key1", "Test App")
        data = _parse_yaml(result)
        assert data["groups"] == {}


class TestSnapshotGroupOrganization:
    """Tests for groups organized by ad_format."""

    def test_single_format(self) -> None:
        """Groups of a single format are organized under that format key."""
        groups = [
            _make_group("US Tier 1", "interstitial", ["US"], 1),
            _make_group("EU Tier 2", "interstitial", ["DE", "FR"], 2),
        ]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        assert "interstitial" in data["groups"]
        assert len(data["groups"]["interstitial"]) == 2

    def test_multiple_formats(self) -> None:
        """Groups of different formats are organized under separate keys."""
        groups = [
            _make_group("US Tier 1", "interstitial", ["US"], 1),
            _make_group("US Rewarded", "rewarded", ["US"], 1),
            _make_group("Banner All", "banner", ["US"], 1),
        ]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        assert "interstitial" in data["groups"]
        assert "rewarded" in data["groups"]
        assert "banner" in data["groups"]
        assert len(data["groups"]["interstitial"]) == 1
        assert len(data["groups"]["rewarded"]) == 1
        assert len(data["groups"]["banner"]) == 1

    def test_groups_with_no_instances(self) -> None:
        """Groups with no instances have an empty instances list."""
        groups = [_make_group("US Tier 1", "interstitial")]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["interstitial"][0]
        assert group_data["instances"] == []


class TestSnapshotFieldMapping:
    """Tests for correct field name simplification."""

    def test_group_name_mapped_to_name(self) -> None:
        """group_name is mapped to 'name' in output."""
        groups = [_make_group("US Tier 1", "interstitial")]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["interstitial"][0]
        assert group_data["name"] == "US Tier 1"
        assert "group_name" not in group_data

    def test_group_id_preserved(self) -> None:
        """group_id is preserved as-is."""
        groups = [_make_group("US Tier 1", "interstitial", group_id=42)]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["interstitial"][0]
        assert group_data["group_id"] == 42

    def test_countries_preserved(self) -> None:
        """countries list is preserved."""
        groups = [_make_group("US Tier 1", "interstitial", countries=["US", "CA"])]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["interstitial"][0]
        assert group_data["countries"] == ["US", "CA"]

    def test_position_preserved(self) -> None:
        """position is preserved."""
        groups = [_make_group("US Tier 1", "interstitial", position=3)]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["interstitial"][0]
        assert group_data["position"] == 3

    def test_floor_price_preserved(self) -> None:
        """floor_price is preserved."""
        groups = [_make_group("Floor Test", "interstitial", floor_price=1.5)]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["interstitial"][0]
        assert group_data["floor_price"] == 1.5

    def test_floor_price_none(self) -> None:
        """floor_price is included as null when None."""
        groups = [_make_group("No Floor", "interstitial")]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["interstitial"][0]
        assert group_data["floor_price"] is None

    def test_ab_test_preserved(self) -> None:
        """ab_test is preserved."""
        groups = [_make_group("AB Test", "interstitial", ab_test="experiment_123")]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["interstitial"][0]
        assert group_data["ab_test"] == "experiment_123"

    def test_ab_test_none(self) -> None:
        """ab_test is included as null when None."""
        groups = [_make_group("No AB", "interstitial")]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["interstitial"][0]
        assert group_data["ab_test"] is None


class TestSnapshotInstances:
    """Tests for instance serialization with field mapping."""

    def test_instance_id_mapped_to_id(self) -> None:
        """instance_id is mapped to 'id' in output."""
        inst = _make_instance(instance_id=42)
        groups = [_make_group("US Tier 1", "interstitial", instances=[inst])]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        instance_data = data["groups"]["interstitial"][0]["instances"][0]
        assert instance_data["id"] == 42
        assert "instance_id" not in instance_data

    def test_instance_name_mapped_to_name(self) -> None:
        """instance_name is mapped to 'name' in output."""
        inst = _make_instance(name="AdMob Banner")
        groups = [_make_group("US Tier 1", "interstitial", instances=[inst])]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        instance_data = data["groups"]["interstitial"][0]["instances"][0]
        assert instance_data["name"] == "AdMob Banner"
        assert "instance_name" not in instance_data

    def test_network_name_mapped_to_network(self) -> None:
        """network_name is mapped to 'network' in output."""
        inst = _make_instance(network="AdMob")
        groups = [_make_group("US Tier 1", "interstitial", instances=[inst])]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        instance_data = data["groups"]["interstitial"][0]["instances"][0]
        assert instance_data["network"] == "AdMob"
        assert "network_name" not in instance_data

    def test_is_bidder_preserved(self) -> None:
        """is_bidder is preserved."""
        inst = _make_instance(is_bidder=True)
        groups = [_make_group("US Tier 1", "interstitial", instances=[inst])]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        instance_data = data["groups"]["interstitial"][0]["instances"][0]
        assert instance_data["is_bidder"] is True

    def test_group_rate_mapped_to_rate(self) -> None:
        """group_rate is mapped to 'rate' in output."""
        inst = _make_instance(group_rate=1.25)
        groups = [_make_group("US Tier 1", "interstitial", instances=[inst])]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        instance_data = data["groups"]["interstitial"][0]["instances"][0]
        assert instance_data["rate"] == 1.25
        assert "group_rate" not in instance_data

    def test_rate_omitted_when_none(self) -> None:
        """rate field is omitted when group_rate is None."""
        inst = _make_instance(group_rate=None)
        groups = [_make_group("US Tier 1", "interstitial", instances=[inst])]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        instance_data = data["groups"]["interstitial"][0]["instances"][0]
        assert "rate" not in instance_data

    def test_multiple_instances(self) -> None:
        """Multiple instances are serialized in order."""
        inst1 = _make_instance(instance_id=1, name="ironSource", network="ironSource")
        inst2 = _make_instance(instance_id=2, name="AdMob", network="AdMob")
        groups = [_make_group("US Tier 1", "interstitial", instances=[inst1, inst2])]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        instances = data["groups"]["interstitial"][0]["instances"]
        assert len(instances) == 2
        assert instances[0]["id"] == 1
        assert instances[1]["id"] == 2


class TestSnapshotRoundTrip:
    """Tests for full round-trip YAML validity."""

    def test_full_snapshot_parseable(self) -> None:
        """A full snapshot with multiple groups and instances is valid YAML."""
        inst1 = _make_instance(instance_id=1, name="IS Default", network="ironSource", group_rate=0.5)
        inst2 = _make_instance(instance_id=2, name="AdMob Banner", network="AdMob", group_rate=None)

        groups = [
            _make_group(
                "US Tier 1", "interstitial", ["US"], 1,
                group_id=100, floor_price=2.0, ab_test=None,
                instances=[inst1, inst2],
            ),
            _make_group(
                "EU Tier 2", "interstitial", ["DE", "FR", "GB"], 2,
                group_id=101, floor_price=None, ab_test="exp_1",
                instances=[inst1],
            ),
            _make_group(
                "US Rewarded", "rewarded", ["US"], 1,
                group_id=200, instances=[],
            ),
        ]

        result = generate_snapshot(groups, "abc123", "Shelf Sort", platform=Platform.IOS)
        data = _parse_yaml(result)

        # Top-level
        assert data["app_key"] == "abc123"
        assert data["app_name"] == "Shelf Sort"
        assert data["platform"] == "iOS"

        # Groups by format
        assert "interstitial" in data["groups"]
        assert "rewarded" in data["groups"]
        assert len(data["groups"]["interstitial"]) == 2
        assert len(data["groups"]["rewarded"]) == 1

        # First interstitial group detail
        g1 = data["groups"]["interstitial"][0]
        assert g1["name"] == "US Tier 1"
        assert g1["group_id"] == 100
        assert g1["countries"] == ["US"]
        assert g1["position"] == 1
        assert g1["floor_price"] == 2.0
        assert g1["ab_test"] is None
        assert len(g1["instances"]) == 2
        assert g1["instances"][0]["rate"] == 0.5
        assert "rate" not in g1["instances"][1]  # None rate omitted

        # Second interstitial group
        g2 = data["groups"]["interstitial"][1]
        assert g2["name"] == "EU Tier 2"
        assert g2["ab_test"] == "exp_1"
        assert len(g2["instances"]) == 1

        # Rewarded group (no instances)
        g3 = data["groups"]["rewarded"][0]
        assert g3["name"] == "US Rewarded"
        assert g3["instances"] == []

    def test_group_id_none_serialized(self) -> None:
        """Groups with group_id=None serialize correctly."""
        groups = [_make_group("New Group", "banner", group_id=None)]
        result = generate_snapshot(groups, "key1", "Test App")
        data = _parse_yaml(result)
        group_data = data["groups"]["banner"][0]
        assert group_data["group_id"] is None


class TestSnapshotImport:
    """Tests for module import accessibility."""

    def test_import_from_engine(self) -> None:
        """generate_snapshot is importable from admedi.engine."""
        from admedi.engine import generate_snapshot as gs
        assert callable(gs)

    def test_import_directly(self) -> None:
        """generate_snapshot is importable from admedi.engine.snapshot."""
        from admedi.engine.snapshot import generate_snapshot as gs
        assert callable(gs)
