"""YAML template loader for portfolio tier configs and settings files.

Reads YAML files from disk, parses them via ``ruamel.yaml`` (safe mode),
and validates the results into Pydantic models.

Seven loaders are provided:

1. ``load_template()`` -- Reads a full portfolio tier template (with
   ``schema_version``, ``mediator``, ``portfolio``, and ``tiers`` keys)
   and returns a ``PortfolioConfig``.

2. ``load_tiers_settings()`` -- (Legacy) Reads a tiers settings file
   (generated by ``admedi pull``) with a ``tiers`` dict mapping tier
   names to their country lists and format associations, and returns a
   ``list[PortfolioTier]``.

3. ``load_country_groups()`` -- Reads a ``countries.yaml`` file defining
   portfolio-wide named country groups (group name -> country code list),
   validates country codes (``^[A-Z]{2}$``), and returns a dict.

4. ``load_tiers_definition()`` -- Reads a ``tiers.yaml`` file mapping
   tier names to country group references (strings), validates that
   references resolve in the country groups dict, and returns a dict.

5. ``load_profiles()`` -- Reads a ``profiles.yaml`` file mapping app
   aliases to expanded profile data (``app_key``, ``app_name``,
   ``platform``), and returns a dict of alias -> ``Profile``.

6. ``resolve_app_tiers()`` -- Two-layer resolution: reads a per-app
   settings file (``settings/{alias}.yaml``), resolves country group
   references via ``countries.yaml``, and returns a
   ``list[PortfolioTier]`` (one per format-tier combination).

7. ``load_network_presets()`` -- Reads a ``networks.yaml`` file defining
   portfolio-wide named network waterfall presets. Each preset maps to a
   list of instance entries with ``network`` (str) and ``bidder`` (bool)
   fields. Returns a ``dict[str, list[dict[str, Any]]]``.

The loader is synchronous (no async I/O). If the calling orchestrator
needs non-blocking behavior, it can wrap the loader in
``asyncio.to_thread()``.

Error handling strategy:
- ``FileNotFoundError`` propagates directly (file does not exist).
- ``ruamel.yaml.YAMLError`` is caught and re-raised as
  ``ConfigValidationError`` with a human-readable message.
- Pydantic ``ValidationError`` is caught and re-raised as
  ``ConfigValidationError`` with a human-readable message.

Examples:
    >>> from admedi.engine.loader import load_template, resolve_app_tiers
    >>> config = load_template("examples/shelf-sort-tiers.yaml")
    >>> config.mediator
    <Mediator.LEVELPLAY: 'levelplay'>
    >>> len(config.tiers)
    4
    >>> tiers = resolve_app_tiers("hexar-ios")
    >>> len(tiers)
    4
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field, ValidationError
from ruamel.yaml import YAML, YAMLError

from admedi.exceptions import ConfigValidationError
from admedi.models.enums import AdFormat, Platform
from admedi.models.portfolio import PortfolioConfig, PortfolioTier


# ---------------------------------------------------------------------------
# Profile model
# ---------------------------------------------------------------------------


class Profile(BaseModel):
    """App identity profile from ``profiles.yaml``.

    Each alias in the profiles file maps to a Profile containing the full
    app identity: app_key (LevelPlay API key), app_name (human-readable),
    and platform (iOS/Android/Amazon).

    Examples:
        >>> profile = Profile(
        ...     alias="hexar-ios",
        ...     app_key="676996cd",
        ...     app_name="Hexar.io iOS",
        ...     platform=Platform.IOS,
        ... )
        >>> profile.app_key
        '676996cd'
    """

    alias: str = Field(description="Profile alias (e.g., 'hexar-ios')")
    app_key: str = Field(description="LevelPlay app key")
    app_name: str = Field(description="Human-readable app name")
    platform: Platform = Field(description="Target platform")

# Regex for valid ISO 3166-1 alpha-2 country codes (2 uppercase ASCII letters).
_COUNTRY_CODE_PATTERN: re.Pattern[str] = re.compile(r"^[A-Z]{2}$")


def load_template(path: str | Path) -> PortfolioConfig:
    """Load and validate a YAML tier template into a PortfolioConfig.

    .. deprecated::
        No longer exported from ``admedi.engine`` or imported by production
        code.  Retained in source for reference only.  The three-layer
        settings architecture (``resolve_app_tiers()``) replaces this
        function.

    Reads the YAML file at ``path``, parses it with safe YAML loading
    (no arbitrary code execution), and validates the parsed data into
    a ``PortfolioConfig`` pydantic model.

    Args:
        path: File system path to the YAML tier template. Accepts
            both string paths and ``pathlib.Path`` objects.

    Returns:
        A validated ``PortfolioConfig`` instance.

    Raises:
        FileNotFoundError: If the template file does not exist.
        ConfigValidationError: If the YAML is malformed or the
            parsed data fails ``PortfolioConfig`` validation.

    Examples:
        >>> config = load_template("examples/shelf-sort-tiers.yaml")
        >>> config.schema_version
        1
    """
    file_path = Path(path)

    if not file_path.exists():
        raise FileNotFoundError(
            f"Template file not found: {file_path}"
        )

    yaml = YAML(typ="safe")

    try:
        raw_data = yaml.load(file_path)
    except YAMLError as exc:
        raise ConfigValidationError(
            f"Malformed YAML in '{file_path.name}': {exc}",
            detail=str(exc),
        ) from exc

    if raw_data is None:
        raise ConfigValidationError(
            f"Template file '{file_path.name}' is empty or contains no YAML data"
        )

    if not isinstance(raw_data, dict):
        raise ConfigValidationError(
            f"Template file '{file_path.name}' must contain a YAML mapping "
            f"(got {type(raw_data).__name__})"
        )

    try:
        return PortfolioConfig.model_validate(raw_data)
    except ValidationError as exc:
        # Extract the first human-readable error message from pydantic
        errors = exc.errors()
        if errors:
            first_error = errors[0]
            location = " -> ".join(str(loc) for loc in first_error.get("loc", []))
            message = first_error.get("msg", str(exc))
            if location:
                friendly = f"Validation error in '{file_path.name}' at {location}: {message}"
            else:
                friendly = f"Validation error in '{file_path.name}': {message}"
        else:
            friendly = f"Validation error in '{file_path.name}': {exc}"

        raise ConfigValidationError(
            friendly,
            detail=str(exc),
        ) from exc


# ---------------------------------------------------------------------------
# Country groups loader
# ---------------------------------------------------------------------------


def load_country_groups(settings_dir: str = "settings") -> dict[str, list[str]]:
    """Load and validate portfolio-wide country group definitions.

    Reads ``countries.yaml`` from the project root (resolved as
    ``Path(settings_dir).parent``). The file is a simple YAML mapping of
    group name to country code list.

    Convention: ``settings_dir`` must be structured so ``.parent`` yields
    the project root containing ``countries.yaml``. The default
    ``"settings"`` works when CWD is the project root; CLI callers should
    pass absolute paths for robustness.

    Args:
        settings_dir: Path to the settings directory. The parent of this
            path is treated as the project root containing
            ``countries.yaml``.

    Returns:
        A dict mapping group name (str) to a list of 2-letter uppercase
        country codes (list[str]).

    Raises:
        FileNotFoundError: If ``countries.yaml`` does not exist.
        ConfigValidationError: If the YAML is malformed, empty, not a
            mapping, or contains invalid country codes.

    Examples:
        >>> groups = load_country_groups("settings")  # doctest: +SKIP
        >>> groups["US"]  # doctest: +SKIP
        ['US']
        >>> "AU" in groups["high-value"]  # doctest: +SKIP
        True
    """
    project_root = Path(settings_dir).parent
    file_path = project_root / "countries.yaml"

    if not file_path.exists():
        raise FileNotFoundError(
            f"Country groups file not found: {file_path}"
        )

    yaml = YAML(typ="safe")

    try:
        raw_data = yaml.load(file_path)
    except YAMLError as exc:
        raise ConfigValidationError(
            f"Malformed YAML in '{file_path.name}': {exc}",
            detail=str(exc),
        ) from exc

    if raw_data is None:
        raise ConfigValidationError(
            f"Country groups file '{file_path.name}' is empty or contains no YAML data"
        )

    if not isinstance(raw_data, dict):
        raise ConfigValidationError(
            f"Country groups file '{file_path.name}' must contain a YAML mapping "
            f"(got {type(raw_data).__name__})"
        )

    result: dict[str, list[str]] = {}

    for group_name, country_list in raw_data.items():
        # Each value must be a non-empty list
        if not isinstance(country_list, list) or len(country_list) == 0:
            raise ConfigValidationError(
                f"Country group '{group_name}' in '{file_path.name}' "
                f"must be a non-empty list of country codes"
            )

        # Check for duplicates within this group
        seen: set[str] = set()
        for code in country_list:
            if not isinstance(code, str):
                raise ConfigValidationError(
                    f"Invalid country code {code!r} in group '{group_name}' "
                    f"of '{file_path.name}': must be a string"
                )

            if not _COUNTRY_CODE_PATTERN.match(code):
                raise ConfigValidationError(
                    f"Invalid country code '{code}' in group '{group_name}' "
                    f"of '{file_path.name}': must be 2 uppercase letters (e.g., 'US')"
                )

            if code in seen:
                raise ConfigValidationError(
                    f"Duplicate country code '{code}' in group '{group_name}' "
                    f"of '{file_path.name}'"
                )
            seen.add(code)

        result[group_name] = list(country_list)

    return result


# ---------------------------------------------------------------------------
# Tiers definition loader
# ---------------------------------------------------------------------------


def load_tiers_definition(
    settings_dir: str = "settings",
    country_groups: dict[str, list[str]] | None = None,
) -> dict[str, str]:
    """Load and validate portfolio-wide tier definitions from ``tiers.yaml``.

    Reads ``tiers.yaml`` from the project root (resolved as
    ``Path(settings_dir).parent``, same convention as
    ``load_country_groups()``). The file is a YAML mapping of tier name to
    country group reference (a string -- either a group name defined in
    ``countries.yaml`` or the ``'*'`` literal for a catch-all tier).

    The returned dict maps tier name to country group reference string.
    Resolution to actual country codes happens later at
    ``resolve_app_tiers()`` time.

    If ``country_groups`` is not provided, ``load_country_groups()`` is
    called internally to load them from ``countries.yaml``.

    Args:
        settings_dir: Path to the settings directory. The parent of this
            path is treated as the project root containing
            ``tiers.yaml`` and ``countries.yaml``.
        country_groups: Pre-loaded country groups dict. If ``None``,
            ``load_country_groups()`` is called to load them.

    Returns:
        A dict mapping tier name (str) to country group reference (str).

    Raises:
        FileNotFoundError: If ``tiers.yaml`` does not exist.
        ConfigValidationError: If the YAML is malformed, empty, not a
            mapping, contains fewer than one tier, has non-string values,
            references a non-existent country group, or has two tiers
            resolving to the same country set.

    Examples:
        >>> tiers = load_tiers_definition("settings")  # doctest: +SKIP
        >>> tiers["Tier 1"]  # doctest: +SKIP
        'US'
        >>> tiers["All Countries"]  # doctest: +SKIP
        '*'
    """
    project_root = Path(settings_dir).parent
    file_path = project_root / "tiers.yaml"

    if not file_path.exists():
        raise FileNotFoundError(
            f"Tiers definition file not found: {file_path}"
        )

    yaml = YAML(typ="safe")

    try:
        raw_data = yaml.load(file_path)
    except YAMLError as exc:
        raise ConfigValidationError(
            f"Malformed YAML in '{file_path.name}': {exc}",
            detail=str(exc),
        ) from exc

    if raw_data is None:
        raise ConfigValidationError(
            f"Tiers definition file '{file_path.name}' is empty or contains no YAML data"
        )

    if not isinstance(raw_data, dict):
        raise ConfigValidationError(
            f"Tiers definition file '{file_path.name}' must contain a YAML mapping "
            f"(got {type(raw_data).__name__})"
        )

    if len(raw_data) == 0:
        raise ConfigValidationError(
            f"Tiers definition file '{file_path.name}' must define at least one tier"
        )

    # Load country groups if not provided
    if country_groups is None:
        country_groups = load_country_groups(settings_dir=settings_dir)

    # Validate each tier entry
    result: dict[str, str] = {}
    # Track resolved country sets (as frozensets) to detect duplicates.
    # The '*' catch-all tier is excluded from this check.
    resolved_sets: dict[frozenset[str], str] = {}

    for tier_name, group_ref in raw_data.items():
        # Each tier value must be a string
        if not isinstance(group_ref, str):
            raise ConfigValidationError(
                f"Tier '{tier_name}' in '{file_path.name}' must reference a "
                f"country group name (string), got {type(group_ref).__name__}"
            )

        # '*' is a valid catch-all -- skip group resolution check
        if group_ref != "*":
            if group_ref not in country_groups:
                raise ConfigValidationError(
                    f"Tier '{tier_name}' in '{file_path.name}' references "
                    f"country group '{group_ref}' which does not exist in "
                    f"countries.yaml"
                )

            # Check for duplicate resolved country sets
            resolved = frozenset(country_groups[group_ref])
            if resolved in resolved_sets:
                existing_tier = resolved_sets[resolved]
                raise ConfigValidationError(
                    f"Tiers '{existing_tier}' and '{tier_name}' in "
                    f"'{file_path.name}' resolve to the same country set "
                    f"(via groups '{country_groups[group_ref]}'); "
                    f"each tier must have a unique country set"
                )
            resolved_sets[resolved] = tier_name

        result[tier_name] = group_ref

    return result


# ---------------------------------------------------------------------------
# Tiers settings loader
# ---------------------------------------------------------------------------

# Valid AdFormat values for tiers settings files (strings, for validation).
_VALID_FORMAT_VALUES: set[str] = {f.value for f in AdFormat if f != AdFormat.REWARDED_VIDEO}


def load_tiers_settings(
    alias: str, settings_dir: str = "settings"
) -> list[PortfolioTier]:
    """Load a tiers settings file and return a list of PortfolioTier objects.

    .. deprecated::
        No longer exported from ``admedi.engine`` or imported by production
        code.  Retained in source for reference only.  The three-layer
        settings architecture (``resolve_app_tiers()``) replaces this
        function.

    Reads ``{settings_dir}/{alias}-tiers.yaml``, parses the ``tiers``
    top-level key (a dict of tier_name -> {countries, formats}), and
    converts each entry into a ``PortfolioTier``.

    Translation rules from the tiers file dict to ``PortfolioTier``:

    - Dict key -> ``tier.name``
    - ``countries`` field -> ``tier.countries``
    - ``formats`` field -> ``tier.ad_formats`` (string values to ``AdFormat`` enums)
    - Overall dict order -> ``tier.position`` (1-based index)
    - ``'*'`` in countries -> ``tier.is_default = True``

    Args:
        alias: App alias used to locate the tiers file (e.g., ``"hexar-ios"``
            reads ``settings/hexar-ios-tiers.yaml``).
        settings_dir: Directory containing settings files.

    Returns:
        A list of ``PortfolioTier`` instances derived from the settings file.

    Raises:
        FileNotFoundError: If the tiers settings file does not exist.
        ConfigValidationError: If the YAML is malformed, the ``tiers``
            key is missing, or a format string is invalid.

    Examples:
        >>> tiers = load_tiers_settings("hexar-ios")  # doctest: +SKIP
        >>> len(tiers)  # doctest: +SKIP
        4
        >>> tiers[0].name  # doctest: +SKIP
        'Tier 1'
    """
    file_path = Path(settings_dir) / f"{alias}-tiers.yaml"

    if not file_path.exists():
        raise FileNotFoundError(
            f"Tiers settings file not found: {file_path}"
        )

    yaml = YAML(typ="safe")

    try:
        raw_data = yaml.load(file_path)
    except YAMLError as exc:
        raise ConfigValidationError(
            f"Malformed YAML in '{file_path.name}': {exc}",
            detail=str(exc),
        ) from exc

    if raw_data is None or not isinstance(raw_data, dict):
        raise ConfigValidationError(
            f"Tiers settings file '{file_path.name}' must contain a YAML mapping"
        )

    if "tiers" not in raw_data:
        raise ConfigValidationError(
            f"Tiers settings file '{file_path.name}' is missing required 'tiers' key"
        )

    tiers_dict = raw_data["tiers"]

    # Empty tiers dict -> empty list
    if not tiers_dict:
        return []

    if not isinstance(tiers_dict, dict):
        raise ConfigValidationError(
            f"'tiers' key in '{file_path.name}' must be a mapping, "
            f"got {type(tiers_dict).__name__}"
        )

    result: list[PortfolioTier] = []
    for position, (tier_name, tier_data) in enumerate(tiers_dict.items(), start=1):
        countries: list[str] = tier_data.get("countries", [])
        is_default = "*" in countries

        # Parse formats field (convert strings to AdFormat enums)
        format_strings: list[str] = tier_data.get("formats", [])
        ad_formats: list[AdFormat] = []
        for fmt_str in format_strings:
            if fmt_str not in _VALID_FORMAT_VALUES:
                raise ConfigValidationError(
                    f"Invalid ad format '{fmt_str}' in tier '{tier_name}' "
                    f"of '{file_path.name}': must be one of {sorted(_VALID_FORMAT_VALUES)}"
                )
            ad_formats.append(AdFormat(fmt_str))

        result.append(
            PortfolioTier(
                name=tier_name,
                countries=countries,
                position=position,
                is_default=is_default,
                ad_formats=ad_formats,
            )
        )

    return result


# ---------------------------------------------------------------------------
# Two-layer resolution: per-app settings -> countries.yaml
# ---------------------------------------------------------------------------


def resolve_app_tiers(
    alias: str, settings_dir: str = "settings"
) -> list[PortfolioTier]:
    """Resolve per-app settings through the two-layer config chain.

    Reads ``{settings_dir}/{alias}.yaml`` in the per-app format (``alias``
    field + ad format sections, each a list of ``display_name: group_ref``
    mappings), then resolves country group references via ``countries.yaml``
    to produce a flat ``list[PortfolioTier]``.

    Each format-tier combination produces one ``PortfolioTier`` (Option A):
    simpler logic, supports per-format position differences, and the
    differ's ``_build_template_format_map()`` already handles single-format
    tiers.

    Resolution pipeline:
        1. Parse ``settings/{alias}.yaml`` -- ``alias`` field + format sections
        2. Validate ``alias`` field matches caller's ``alias`` parameter
        3. Validate ``alias`` exists in ``profiles.yaml``
        4. Resolve country group references via ``load_country_groups()``
        5. For each format section, for each entry (position = index + 1):
           create ``PortfolioTier(name, countries, position, [format], is_default)``

    Args:
        alias: App alias used to locate the per-app settings file
            (e.g., ``"hexar-ios"`` reads ``settings/hexar-ios.yaml``).
        settings_dir: Directory containing per-app settings files.
            Root-level files (``countries.yaml``, ``profiles.yaml``) are
            resolved from ``Path(settings_dir).parent``.

    Returns:
        A list of ``PortfolioTier`` instances, one per format-tier combination.

    Raises:
        FileNotFoundError: If the per-app settings file does not exist.
        ConfigValidationError: If the YAML is malformed, the ``alias``
            field is missing or mismatched, a country group reference is
            not found in ``countries.yaml``, or a format section key is
            invalid.

    Examples:
        >>> tiers = resolve_app_tiers("hexar-ios")  # doctest: +SKIP
        >>> len(tiers)  # doctest: +SKIP
        6
        >>> tiers[0].name  # doctest: +SKIP
        'Tier 1'
        >>> tiers[0].ad_formats  # doctest: +SKIP
        [<AdFormat.REWARDED: 'rewarded'>]
    """
    settings_path = Path(settings_dir)
    file_path = settings_path / f"{alias}.yaml"

    if not file_path.exists():
        raise FileNotFoundError(
            f"Per-app settings file not found: {file_path}"
        )

    yaml = YAML(typ="safe")

    try:
        raw_data = yaml.load(file_path)
    except YAMLError as exc:
        raise ConfigValidationError(
            f"Malformed YAML in '{file_path.name}': {exc}",
            detail=str(exc),
        ) from exc

    if raw_data is None or not isinstance(raw_data, dict):
        raise ConfigValidationError(
            f"Per-app settings file '{file_path.name}' must contain a YAML mapping"
        )

    # --- Validate alias field ---
    if "alias" not in raw_data:
        raise ConfigValidationError(
            f"Per-app settings file '{file_path.name}' is missing required "
            f"'alias' field"
        )

    file_alias = raw_data["alias"]
    if not isinstance(file_alias, str):
        raise ConfigValidationError(
            f"'alias' field in '{file_path.name}' must be a string, "
            f"got {type(file_alias).__name__}"
        )

    if file_alias != alias:
        raise ConfigValidationError(
            f"Alias mismatch in '{file_path.name}': file says "
            f"alias '{file_alias}' but resolve_app_tiers() was called "
            f"with alias '{alias}'"
        )

    # --- Validate alias exists in profiles.yaml ---
    project_root = settings_path.parent
    profiles_path = project_root / "profiles.yaml"
    profiles = load_profiles(profiles_path)
    if alias not in profiles:
        available = ", ".join(sorted(profiles.keys()))
        raise ConfigValidationError(
            f"Alias '{alias}' not found in profiles.yaml. "
            f"Available profiles: {available}"
        )

    # --- Load country group definitions ---
    country_groups = load_country_groups(settings_dir=settings_dir)

    # --- Parse format sections and resolve entries ---
    result: list[PortfolioTier] = []

    for key, value in raw_data.items():
        # Skip metadata keys (currently only 'alias')
        if key == "alias":
            continue

        # Validate format key
        if key not in _VALID_FORMAT_VALUES:
            raise ConfigValidationError(
                f"Invalid format section '{key}' in '{file_path.name}': "
                f"must be one of {sorted(_VALID_FORMAT_VALUES)}"
            )

        ad_format = AdFormat(key)

        # Value must be a list of entries (or empty list)
        if not isinstance(value, list):
            raise ConfigValidationError(
                f"Format section '{key}' in '{file_path.name}' must be "
                f"a list of tier names, got {type(value).__name__}"
            )

        for position, entry in enumerate(value, start=1):
            # Entry must be a single-key dict (display_name: group_ref)
            if isinstance(entry, str):
                raise ConfigValidationError(
                    f"Tier entry in format section '{key}' of '{file_path.name}' "
                    f"must be a mapping (e.g., 'Tier 1: US'), got plain string '{entry}'. "
                    f"Run 'admedi pull --app {alias}' to regenerate settings."
                )
            if not isinstance(entry, dict) or len(entry) != 1:
                raise ConfigValidationError(
                    f"Tier entry in format section '{key}' of '{file_path.name}' "
                    f"must be a single-key mapping (e.g., 'Tier 1: US')"
                )

            display_name = next(iter(entry))
            entry_value = entry[display_name]

            # Entry value must be a dict: {countries: ref, networks: ref}
            if not isinstance(entry_value, dict):
                raise ConfigValidationError(
                    f"Tier entry '{display_name}' in format section '{key}' "
                    f"of '{file_path.name}' must be a dict "
                    f"(e.g., '{{countries: US, networks: bidding-6}}'). "
                    f"Run 'admedi pull --app {alias}' to regenerate settings."
                )

            if "countries" not in entry_value:
                raise ConfigValidationError(
                    f"Tier entry '{display_name}' in format section '{key}' "
                    f"of '{file_path.name}' is missing required 'countries' key"
                )

            group_ref = entry_value["countries"]
            network_ref = entry_value.get("networks")

            # Resolve country group reference -> country codes
            if group_ref == "*":
                countries = ["*"]
                is_default = True
            else:
                if group_ref not in country_groups:
                    raise ConfigValidationError(
                        f"Country group '{group_ref}' (referenced by "
                        f"'{display_name}' in format section '{key}') "
                        f"not found in countries.yaml"
                    )
                countries = country_groups[group_ref]
                is_default = False

            result.append(
                PortfolioTier(
                    name=display_name,
                    countries=countries,
                    position=position,
                    is_default=is_default,
                    ad_formats=[ad_format],
                    network_preset=network_ref,
                )
            )

    return result


# ---------------------------------------------------------------------------
# Profiles loader
# ---------------------------------------------------------------------------


def load_profiles(
    profiles_path: str | Path = "profiles.yaml",
) -> dict[str, Profile]:
    """Load and validate app profiles from ``profiles.yaml``.

    Reads the ``profiles`` top-level key from the YAML file and returns
    a dict mapping alias to ``Profile``. Each alias entry must provide
    ``app_key`` (non-empty string), ``app_name`` (string), and
    ``platform`` (valid ``Platform`` enum value).

    Args:
        profiles_path: Path to the profiles YAML file. Defaults to
            ``"profiles.yaml"`` (project root convention).

    Returns:
        A dict mapping alias (str) to ``Profile`` instance.

    Raises:
        FileNotFoundError: If the profiles file does not exist.
        ConfigValidationError: If the YAML is malformed, the ``profiles``
            key is missing, or an alias entry is missing required fields
            or has invalid values.

    Examples:
        >>> profiles = load_profiles("profiles.yaml")  # doctest: +SKIP
        >>> profiles["hexar-ios"].app_key  # doctest: +SKIP
        '676996cd'
        >>> profiles["hexar-ios"].platform  # doctest: +SKIP
        <Platform.IOS: 'iOS'>
    """
    file_path = Path(profiles_path)

    if not file_path.exists():
        raise FileNotFoundError(
            f"Profiles file not found: {file_path}"
        )

    yaml = YAML(typ="safe")

    try:
        raw_data = yaml.load(file_path)
    except YAMLError as exc:
        raise ConfigValidationError(
            f"Malformed YAML in '{file_path.name}': {exc}",
            detail=str(exc),
        ) from exc

    if raw_data is None or not isinstance(raw_data, dict):
        raise ConfigValidationError(
            f"Profiles file '{file_path.name}' must contain a YAML mapping"
        )

    if "profiles" not in raw_data:
        raise ConfigValidationError(
            f"Profiles file '{file_path.name}' is missing required 'profiles' key"
        )

    profiles_dict = raw_data["profiles"]

    if not isinstance(profiles_dict, dict):
        raise ConfigValidationError(
            f"'profiles' key in '{file_path.name}' must be a mapping, "
            f"got {type(profiles_dict).__name__}"
        )

    result: dict[str, Profile] = {}

    for alias, entry in profiles_dict.items():
        if not isinstance(entry, dict):
            raise ConfigValidationError(
                f"Profile '{alias}' in '{file_path.name}' must be a mapping "
                f"with app_key, app_name, and platform fields"
            )

        # Validate required fields
        if "app_key" not in entry or not entry["app_key"]:
            raise ConfigValidationError(
                f"Profile '{alias}' in '{file_path.name}' is missing "
                f"required 'app_key' field (must be a non-empty string)"
            )

        if not isinstance(entry["app_key"], str):
            raise ConfigValidationError(
                f"Profile '{alias}' in '{file_path.name}' has invalid "
                f"'app_key': must be a string, got {type(entry['app_key']).__name__}"
            )

        if "app_name" not in entry:
            raise ConfigValidationError(
                f"Profile '{alias}' in '{file_path.name}' is missing "
                f"required 'app_name' field"
            )

        if not isinstance(entry["app_name"], str):
            raise ConfigValidationError(
                f"Profile '{alias}' in '{file_path.name}' has invalid "
                f"'app_name': must be a string, got {type(entry['app_name']).__name__}"
            )

        if "platform" not in entry:
            raise ConfigValidationError(
                f"Profile '{alias}' in '{file_path.name}' is missing "
                f"required 'platform' field"
            )

        # Validate platform is a valid Platform enum value
        platform_str = entry["platform"]
        try:
            platform = Platform(platform_str)
        except ValueError:
            valid_values = [p.value for p in Platform]
            raise ConfigValidationError(
                f"Profile '{alias}' in '{file_path.name}' has invalid "
                f"'platform' value '{platform_str}': must be one of {valid_values}"
            )

        result[alias] = Profile(
            alias=alias,
            app_key=str(entry["app_key"]),
            app_name=str(entry["app_name"]),
            platform=platform,
        )

    return result


# ---------------------------------------------------------------------------
# Network presets loader
# ---------------------------------------------------------------------------


def load_network_presets(
    settings_dir: str = "settings",
) -> dict[str, list[dict[str, Any]]]:
    """Load and validate portfolio-wide network waterfall presets.

    Reads ``networks.yaml`` from the project root (resolved as
    ``Path(settings_dir).parent``), following the same convention as
    ``load_country_groups()``. The file is a YAML mapping of preset name
    to a list of instance entries.

    Each instance entry must have:
    - ``network`` (str): Ad network name (e.g., "Meta Audience Network")
    - ``bidder`` (bool): Whether this is a bidding instance

    Optional fields:
    - ``name`` (str): Instance display name (for disambiguation)
    - ``rate`` (float): Manual CPM rate

    Args:
        settings_dir: Path to the settings directory. The parent of this
            path is treated as the project root containing
            ``networks.yaml``.

    Returns:
        A dict mapping preset name (str) to a list of instance entry
        dicts (list[dict[str, Any]]).

    Raises:
        FileNotFoundError: If ``networks.yaml`` does not exist.
        ConfigValidationError: If the YAML is malformed, empty, not a
            mapping, or contains entries missing required fields.

    Examples:
        >>> presets = load_network_presets("settings")  # doctest: +SKIP
        >>> len(presets["bidding-6"])  # doctest: +SKIP
        6
        >>> presets["bidding-6"][0]["network"]  # doctest: +SKIP
        'Meta Audience Network'
    """
    project_root = Path(settings_dir).parent
    file_path = project_root / "networks.yaml"

    if not file_path.exists():
        raise FileNotFoundError(
            f"Network presets file not found: {file_path}"
        )

    yaml = YAML(typ="safe")

    try:
        raw_data = yaml.load(file_path)
    except YAMLError as exc:
        raise ConfigValidationError(
            f"Malformed YAML in '{file_path.name}': {exc}",
            detail=str(exc),
        ) from exc

    if raw_data is None:
        raise ConfigValidationError(
            f"Network presets file '{file_path.name}' is empty or contains "
            f"no YAML data"
        )

    if not isinstance(raw_data, dict):
        raise ConfigValidationError(
            f"Network presets file '{file_path.name}' must contain a YAML "
            f"mapping (got {type(raw_data).__name__})"
        )

    result: dict[str, list[dict[str, Any]]] = {}

    for preset_name, entries in raw_data.items():
        if not isinstance(entries, list):
            raise ConfigValidationError(
                f"Preset '{preset_name}' in '{file_path.name}' must be a "
                f"list of instance entries, got {type(entries).__name__}"
            )

        validated_entries: list[dict[str, Any]] = []

        for idx, entry in enumerate(entries):
            if not isinstance(entry, dict):
                raise ConfigValidationError(
                    f"Entry {idx} in preset '{preset_name}' of "
                    f"'{file_path.name}' must be a mapping, "
                    f"got {type(entry).__name__}"
                )

            if "network" not in entry:
                raise ConfigValidationError(
                    f"Entry {idx} in preset '{preset_name}' of "
                    f"'{file_path.name}' is missing required 'network' field"
                )

            if not isinstance(entry["network"], str):
                raise ConfigValidationError(
                    f"Entry {idx} in preset '{preset_name}' of "
                    f"'{file_path.name}' has invalid 'network': must be a "
                    f"string, got {type(entry['network']).__name__}"
                )

            if "bidder" not in entry:
                raise ConfigValidationError(
                    f"Entry {idx} in preset '{preset_name}' of "
                    f"'{file_path.name}' is missing required 'bidder' field"
                )

            if not isinstance(entry["bidder"], bool):
                raise ConfigValidationError(
                    f"Entry {idx} in preset '{preset_name}' of "
                    f"'{file_path.name}' has invalid 'bidder': must be a "
                    f"boolean, got {type(entry['bidder']).__name__}"
                )

            validated_entries.append(dict(entry))

        result[preset_name] = validated_entries

    return result
