"""YAML template loader for portfolio tier configs and settings files.

Reads YAML files from disk, parses them via ``ruamel.yaml`` (safe mode),
and validates the results into Pydantic models.

Two loaders are provided:

1. ``load_template()`` -- Reads a full portfolio tier template (with
   ``schema_version``, ``mediator``, ``portfolio``, and ``tiers`` keys)
   and returns a ``PortfolioConfig``.

2. ``load_tiers_settings()`` -- Reads a tiers settings file (generated by
   ``admedi show``) with a ``tiers`` dict mapping tier names to their
   country lists and format associations, and returns a
   ``list[PortfolioTier]``.

The loader is synchronous (no async I/O). If the calling orchestrator
needs non-blocking behavior, it can wrap the loader in
``asyncio.to_thread()``.

Error handling strategy:
- ``FileNotFoundError`` propagates directly (file does not exist).
- ``ruamel.yaml.YAMLError`` is caught and re-raised as
  ``ConfigValidationError`` with a human-readable message.
- Pydantic ``ValidationError`` is caught and re-raised as
  ``ConfigValidationError`` with a human-readable message.

Examples:
    >>> from admedi.engine.loader import load_template, load_tiers_settings
    >>> config = load_template("examples/shelf-sort-tiers.yaml")
    >>> config.mediator
    <Mediator.LEVELPLAY: 'levelplay'>
    >>> len(config.tiers)
    4
    >>> tiers = load_tiers_settings("hexar-ios")
    >>> len(tiers)
    4
"""

from __future__ import annotations

from pathlib import Path

from pydantic import ValidationError
from ruamel.yaml import YAML, YAMLError

from admedi.exceptions import ConfigValidationError
from admedi.models.enums import AdFormat
from admedi.models.portfolio import PortfolioConfig, PortfolioTier


def load_template(path: str | Path) -> PortfolioConfig:
    """Load and validate a YAML tier template into a PortfolioConfig.

    Reads the YAML file at ``path``, parses it with safe YAML loading
    (no arbitrary code execution), and validates the parsed data into
    a ``PortfolioConfig`` pydantic model.

    Args:
        path: File system path to the YAML tier template. Accepts
            both string paths and ``pathlib.Path`` objects.

    Returns:
        A validated ``PortfolioConfig`` instance.

    Raises:
        FileNotFoundError: If the template file does not exist.
        ConfigValidationError: If the YAML is malformed or the
            parsed data fails ``PortfolioConfig`` validation.

    Examples:
        >>> config = load_template("examples/shelf-sort-tiers.yaml")
        >>> config.schema_version
        1
    """
    file_path = Path(path)

    if not file_path.exists():
        raise FileNotFoundError(
            f"Template file not found: {file_path}"
        )

    yaml = YAML(typ="safe")

    try:
        raw_data = yaml.load(file_path)
    except YAMLError as exc:
        raise ConfigValidationError(
            f"Malformed YAML in '{file_path.name}': {exc}",
            detail=str(exc),
        ) from exc

    if raw_data is None:
        raise ConfigValidationError(
            f"Template file '{file_path.name}' is empty or contains no YAML data"
        )

    if not isinstance(raw_data, dict):
        raise ConfigValidationError(
            f"Template file '{file_path.name}' must contain a YAML mapping "
            f"(got {type(raw_data).__name__})"
        )

    try:
        return PortfolioConfig.model_validate(raw_data)
    except ValidationError as exc:
        # Extract the first human-readable error message from pydantic
        errors = exc.errors()
        if errors:
            first_error = errors[0]
            location = " -> ".join(str(loc) for loc in first_error.get("loc", []))
            message = first_error.get("msg", str(exc))
            if location:
                friendly = f"Validation error in '{file_path.name}' at {location}: {message}"
            else:
                friendly = f"Validation error in '{file_path.name}': {message}"
        else:
            friendly = f"Validation error in '{file_path.name}': {exc}"

        raise ConfigValidationError(
            friendly,
            detail=str(exc),
        ) from exc


# ---------------------------------------------------------------------------
# Tiers settings loader
# ---------------------------------------------------------------------------

# Valid AdFormat values for tiers settings files (strings, for validation).
_VALID_FORMAT_VALUES: set[str] = {f.value for f in AdFormat if f != AdFormat.REWARDED_VIDEO}


def load_tiers_settings(
    alias: str, settings_dir: str = "settings"
) -> list[PortfolioTier]:
    """Load a tiers settings file and return a list of PortfolioTier objects.

    Reads ``{settings_dir}/{alias}-tiers.yaml``, parses the ``tiers``
    top-level key (a dict of tier_name -> {countries, formats}), and
    converts each entry into a ``PortfolioTier``.

    Translation rules from the tiers file dict to ``PortfolioTier``:

    - Dict key -> ``tier.name``
    - ``countries`` field -> ``tier.countries``
    - ``formats`` field -> ``tier.ad_formats`` (string values to ``AdFormat`` enums)
    - Overall dict order -> ``tier.position`` (1-based index)
    - ``'*'`` in countries -> ``tier.is_default = True``

    Args:
        alias: App alias used to locate the tiers file (e.g., ``"hexar-ios"``
            reads ``settings/hexar-ios-tiers.yaml``).
        settings_dir: Directory containing settings files.

    Returns:
        A list of ``PortfolioTier`` instances derived from the settings file.

    Raises:
        FileNotFoundError: If the tiers settings file does not exist.
        ConfigValidationError: If the YAML is malformed, the ``tiers``
            key is missing, or a format string is invalid.

    Examples:
        >>> tiers = load_tiers_settings("hexar-ios")  # doctest: +SKIP
        >>> len(tiers)  # doctest: +SKIP
        4
        >>> tiers[0].name  # doctest: +SKIP
        'Tier 1'
    """
    file_path = Path(settings_dir) / f"{alias}-tiers.yaml"

    if not file_path.exists():
        raise FileNotFoundError(
            f"Tiers settings file not found: {file_path}"
        )

    yaml = YAML(typ="safe")

    try:
        raw_data = yaml.load(file_path)
    except YAMLError as exc:
        raise ConfigValidationError(
            f"Malformed YAML in '{file_path.name}': {exc}",
            detail=str(exc),
        ) from exc

    if raw_data is None or not isinstance(raw_data, dict):
        raise ConfigValidationError(
            f"Tiers settings file '{file_path.name}' must contain a YAML mapping"
        )

    if "tiers" not in raw_data:
        raise ConfigValidationError(
            f"Tiers settings file '{file_path.name}' is missing required 'tiers' key"
        )

    tiers_dict = raw_data["tiers"]

    # Empty tiers dict -> empty list
    if not tiers_dict:
        return []

    if not isinstance(tiers_dict, dict):
        raise ConfigValidationError(
            f"'tiers' key in '{file_path.name}' must be a mapping, "
            f"got {type(tiers_dict).__name__}"
        )

    result: list[PortfolioTier] = []
    for position, (tier_name, tier_data) in enumerate(tiers_dict.items(), start=1):
        countries: list[str] = tier_data.get("countries", [])
        is_default = "*" in countries

        # Parse formats field (convert strings to AdFormat enums)
        format_strings: list[str] = tier_data.get("formats", [])
        ad_formats: list[AdFormat] = []
        for fmt_str in format_strings:
            if fmt_str not in _VALID_FORMAT_VALUES:
                raise ConfigValidationError(
                    f"Invalid ad format '{fmt_str}' in tier '{tier_name}' "
                    f"of '{file_path.name}': must be one of {sorted(_VALID_FORMAT_VALUES)}"
                )
            ad_formats.append(AdFormat(fmt_str))

        result.append(
            PortfolioTier(
                name=tier_name,
                countries=countries,
                position=position,
                is_default=is_default,
                ad_formats=ad_formats,
            )
        )

    return result
