"""Snapshot generator for LevelPlay mediation groups.

Converts a list of ``Group`` models (as returned by ``get_groups()``)
into a structured YAML string organized by ad format.  The output is
designed for AI/machine consumption and human review.

The generated YAML includes:
- Header comments with app metadata and capture timestamp
- Top-level data fields (``app_key``, ``app_name``, optional ``platform``)
- Groups organized by ad format (``interstitial:``, ``rewarded:``, etc.)
- Simplified field names (``network`` instead of ``network_name``, etc.)

Examples:
    >>> from admedi.engine.snapshot import generate_snapshot
    >>> from admedi.models.group import Group
    >>> from admedi.models.instance import Instance
    >>> groups = [
    ...     Group.model_validate({
    ...         "groupName": "US Tier 1",
    ...         "adFormat": "interstitial",
    ...         "countries": ["US"],
    ...         "position": 1,
    ...     })
    ... ]
    >>> yaml_str = generate_snapshot(groups, "abc123", "My App")
    >>> "US Tier 1" in yaml_str
    True
"""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone
from io import StringIO
from typing import Any

from ruamel.yaml import YAML

from admedi.models.enums import Platform
from admedi.models.group import Group


def generate_snapshot(
    groups: list[Group],
    app_key: str,
    app_name: str,
    platform: Platform | None = None,
) -> str:
    """Generate a YAML snapshot from a list of Group models.

    Converts groups into a structured YAML string organized by ad format,
    with simplified field names and header comments containing app metadata
    and a capture timestamp.

    Args:
        groups: List of ``Group`` models to serialize. May be empty.
        app_key: Application key for the snapshot header.
        app_name: Application display name for the snapshot header.
        platform: Optional platform identifier. Included in the YAML
            output when provided.

    Returns:
        A YAML-formatted string with header comments and group data
        organized by ad format. Parseable by ``ruamel.yaml``.

    Examples:
        >>> yaml_str = generate_snapshot([], "key1", "Test App")
        >>> "app_key: key1" in yaml_str
        True
        >>> "groups:" in yaml_str
        True
    """
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Build the data structure
    data: dict[str, Any] = {
        "app_key": app_key,
        "app_name": app_name,
    }

    if platform is not None:
        data["platform"] = platform.value

    # Organize groups by ad_format
    groups_by_format: dict[str, list[dict[str, Any]]] = defaultdict(list)

    for group in groups:
        group_dict = _serialize_group(group)
        groups_by_format[group.ad_format.value].append(group_dict)

    data["groups"] = dict(groups_by_format) if groups_by_format else {}

    # Serialize to YAML with header comments
    yaml = YAML()
    yaml.default_flow_style = False

    stream = StringIO()
    yaml.dump(data, stream)
    yaml_body = stream.getvalue()

    # Build header
    header_lines = [
        "# Generated by admedi snapshot",
        f"# App: {app_name} ({app_key})",
        f"# Captured: {timestamp}",
        "",
    ]
    header = "\n".join(header_lines)

    return header + yaml_body


def _serialize_group(group: Group) -> dict[str, Any]:
    """Serialize a Group model to a simplified dict for YAML output.

    Field mapping:
    - ``group_name`` -> ``name``
    - ``group_id`` -> ``group_id`` (unchanged)
    - ``countries`` -> ``countries`` (unchanged)
    - ``position`` -> ``position`` (unchanged)
    - ``floor_price`` -> ``floor_price`` (unchanged)
    - ``ab_test`` -> ``ab_test`` (unchanged)
    - ``instances`` -> ``instances`` (with simplified instance fields)

    Args:
        group: The Group model to serialize.

    Returns:
        A dict with simplified field names ready for YAML serialization.
    """
    group_dict: dict[str, Any] = {
        "name": group.group_name,
        "group_id": group.group_id,
        "countries": list(group.countries),
        "position": group.position,
        "floor_price": group.floor_price,
        "ab_test": group.ab_test,
    }

    instances_list: list[dict[str, Any]] = []
    if group.instances:
        for instance in group.instances:
            instances_list.append(_serialize_instance(instance))

    group_dict["instances"] = instances_list

    return group_dict


def _serialize_instance(instance: "Instance") -> dict[str, Any]:
    """Serialize an Instance model to a simplified dict for YAML output.

    Field mapping:
    - ``instance_id`` -> ``id``
    - ``instance_name`` -> ``name``
    - ``network_name`` -> ``network``
    - ``is_bidder`` -> ``is_bidder`` (unchanged)
    - ``group_rate`` -> ``rate`` (omitted when None)

    Args:
        instance: The Instance model to serialize.

    Returns:
        A dict with simplified field names. The ``rate`` field is
        omitted when the instance's ``group_rate`` is None.
    """
    from admedi.models.instance import Instance  # noqa: F811

    instance_dict: dict[str, Any] = {
        "id": instance.instance_id,
        "name": instance.instance_name,
        "network": instance.network_name,
        "is_bidder": instance.is_bidder,
    }

    if instance.group_rate is not None:
        instance_dict["rate"] = instance.group_rate

    return instance_dict
